### ISSUE TITLE
Invalid timestamp

### ISSUE THREAD

**Issue by s2tu** [akamai/httpie-edgegrid#11]
I am getting the following error:
ERROR: Problem details: {u'status': 400, u'requestTime': u'2018-01-02T17:52:01Z', u'title': u'Bad request', u'detail': u'Invalid timestamp', u'serverIp': u'xxxxxx', u'instance': u'xxxxxxxxxxxxxt/ccu/v3/delete/url/', u'requestId': u'c5394d1', u'clientIp': u'xxxxxxxxxxx', u'type': u'https://problems.purge.akamaiapis.net/-/pep-authn/request-error', u'method': u'POST'}

I am using the httpie-edgegrid python package to obtain the timestamp.  why is it giving me an invalid timestamp error?

Python 2.7 was used

**Comment by justinrummel** [comment]
When I'm doing a test using `http` with edgegrid, I'm getting expected 200 response... there may be something with your python code.  If you are using python, you may also want to look at [https://github.com/akamai/AkamaiOPEN-edgegrid-python](https://github.com/akamai/AkamaiOPEN-edgegrid-python) library.  It's been working great for me.

``` bash
jrummel@macbook-pro ~> http -A edgegrid -a default: POST :/ccu/v3/delete/cpcode/staging objects:='["######"]'
HTTP/1.1 201 Created
Allow: POST
Connection: keep-alive
Content-Length: 170
Content-Type: application/json
Date: Tue, 02 Jan 2018 18:56:45 GMT
Server: Apache
Vary: Authorization

{
    "detail": "Request accepted",
    "estimatedSeconds": 5,
    "httpStatus": 201,
    "purgeId": "adc0f13a-####-####-####-############",
    "supportId": "17PY1514919405444589-#########"
}
```

**Comment by justinrummel** [comment]
I cloned the api-kickstart and it worked as expected.  Notice, I specifically use python3 and also ccu_v3.py.

``` bash
jrummel@macbook-pro ~/D/GIT> git clone https://github.com/akamai/api-kickstart.git
Cloning into 'api-kickstart'...
remote: Counting objects: 2426, done.
remote: Total 2426 (delta 0), reused 0 (delta 0), pack-reused 2426
Receiving objects: 100% (2426/2426), 2.53 MiB | 11.37 MiB/s, done.
Resolving deltas: 100% (1411/1411), done.
jrummel@macbook-pro ~/D/GIT> cd api-kickstart/examples/python/
jrummel@macbook-pro ~/D/G/a/e/python> pico ccu_v3.py
jrummel@macbook-pro ~/D/G/a/e/python> python3 ccu_v3.py --verbose
Adding invalidate request to queue - {"objects": ["https://www.example.com/test/ipsum.txt"]}
LOG: POST /ccu/v3/invalidate/url 201 application/json
>>>
{
"estimatedSeconds": 5,
"purgeId": "bee9a300-f00f-####-####-############",
"supportId": "17PY1514933607624439-#########",
"httpStatus": 201,
"detail": "Request accepted"
}
<<<

jrummel@macbook-pro ~/D/G/a/e/python> python3 --version
Python 3.6.4
```

I did change the URL in the above output, but that is the correct 201 response code.

**Comment by s2tu** [comment]
Turns out it was my server not being in sync with NTP time.  Closing ticket.
