### ISSUE TITLE
HTTPException('got more than 100 headers',)

### ISSUE THREAD

**Issue by jcheshire** [akamai/httpie-edgegrid#12]
When using Akamai request headers to debug Edge calls, the server will frequently return a large number of debug headers. Unfortunately, the default limit for http.client is 100 headers in the response. We should change that default value in the Akamai EdgeGrid client to 1000.

[Sample solution](https://stackoverflow.com/questions/23055378/http-client-httpexception-got-more-than-100-headers/38815673#38815673).

**Comment by robertolopezlopez** [comment]
Hi @jcheshire ,

Thank you for opening this issue, and sorry to not answer for over 4 years :-D

After looking at this problem for some hours, I can see that it was reported in [the httpie main repository](https://github.com/httpie/httpie/issues/802) in 2019. As they added the `--max-headers` parameter already, I consider that this is already a good fix. Thus I will close this issue. If you have any other concern or think that we still need a fix in `httpie-edgegrid`, please do not hesitate on reopening it.

Regards,

Roberto
