### ISSUE TITLE
allow option to indicate the location of the credentials file

### ISSUE THREAD

**Issue by javiergarza** [akamai/httpie-edgegrid#19]
Seems the credentials are hardcoded to ~/.edgerc 

It will be great to allow people to indicate the location (path+filename) of the file containing the API credentials (similar to what the Akamai CLI does with the --config parameter)

**Comment by robertolopezlopez** [comment]
waiting to get access to the PyPI repositories to be able to release https://github.com/pypa/pypi-support/issues/1886

**Comment by robertolopezlopez** [comment]
Hi,

This enhancement has been finally added to our [latest release](https://github.com/akamai/httpie-edgegrid/releases/tag/v2.0.0). Closing the issue.

Regards,

Roberto
