### ISSUE TITLE
DXE-2025 auth-type error  invalid choice: 'edgegrid' on macos

### ISSUE THREAD

**Issue by swazking123** [akamai/httpie-edgegrid#34]
**Describe the bug**
Did a new install as per the readme.md doc of the plugin and tried running the below command : 
http --auth-type edgegrid -a default: :/diagnostic-tools/v2/ghost-locations/available

But It gives the error : 
`usage:
    http -A/--auth-type {basic, digest, bearer} [METHOD] URL [REQUEST_ITEM ...]

error:
    argument --auth-type/-A: invalid choice: 'edgegrid' (choose from 'basic', 'bearer', 'digest')`

My System Configuration :
- macOS version : 13.1
- httpie version : 3.2.1
- httpie-edgegrid version: 2.1.1

**Comment by Slonimskaia** [comment]
Hi @swazking123,

Thank you for reporting this issue. We will try to reproduce it and come back to you soon.

Thanks,
Tatiana

**Comment by lkowalsk-akamai-com** [comment]
Hi @swazking123 this issue should be resolved now with lates release.
