### ISSUE TITLE
Getting error when trying to use proxy for edgegrid testing

### ISSUE THREAD

**Issue by exk8116** [akamai/httpie-edgegrid#6]
http --proxy=https:https://e7997.dscb.akamaiedge-staging.net --auth-type edgegrid -a obs-test: GET :"/authz/v2/basic-contracts?depth=all" --verify=no

http: error: ProxyError: HTTPSConnectionPool(host='akaa-g7wbplokgl54rfz2-anaqoi574jceh7t2.luna-dev.akamaiapis.net', port=443): Max retries exceeded with url: /authz/v2/basic-contracts?depth=all (Caused by ProxyError('Cannot connect to proxy.', error(54, 'Connection reset by peer'))) while doing GET request to URL: https://akaa-g7wbplokgl54rfz2-anaqoi574jceh7t2.luna-dev.akamaiapis.net/authz/v2/basic-contracts?depth=all

**Comment by synedra** [comment]
This is an issue with your proxy setup, and needs to be resolved locally - the code isn't causing the issue.
