### ISSUE TITLE
DXE-3958 Error when POSTing raw json 

### ISSUE THREAD

**Issue by dvhh** [akamai/httpie-edgegrid#61]
**Describe the bug**
piping json to post on API endpoint on akamai cause the following error
```
http: error: AttributeError: '_io.BufferedReader' object has no attribute 'len'
```

**To Reproduce**
1. run `podman run --pull=always --rm -it -v ~/.edgerc:/root/.edgerc -v $PWD:/workdir:rw docker.io/akamai/shell`
2. run `http -v --auth-type=edgegrid -a default: POST :/identity-management/v3/user-admin/ui-identities < pay
load.json`
3. See error `http: error: AttributeError: '_io.BufferedReader' object has no attribute 'len'`

**Expected behavior**
POST data on the API endpoint and see an answer

**Screenshots**
Not Applicable

**Please complete the following information:**
 - OS: linux
 - Version : 3.2.2

**Additional context**
Playload content does not seem relevant for the issue, suspect the issue is caused by edgegrid authentication trying to read the payload for calculating the request signature.

**Comment by ckulinsk** [comment]
Hi @dvhh 

Thank you for reporting this issue. We were able to reproduce it and will inform you about the progress of fix.

Best regards,
Cyryl

**Comment by dvhh** [comment]
Hello @ckulinsk, 

In the meantime would you kindly recommend any workaround for posting payload to api endpoint. Currently we wrote a python script in order to do it, but we would appreciate to use any Akamai recommended solution.

**Comment by dvhh** [comment]
Hello @wzagrajcz,

This should work for us in the meantime, thanks

**Comment by lkowalsk-akamai-com** [comment]
Hi @dvhh, this issue should be resolved now.
